# Generated by Django 4.0.5 on 2022-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='password',
            field=models.IntegerField(),
        ),
    ]
