# Generated by Django 4.1 on 2022-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='courselist',
            name='certificate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='enroll_course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='lecture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='skill_level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
