# Generated by Django 4.1 on 2022-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_student_courselist_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='certificate',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='enroll_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
