# Generated by Django 4.1 on 2022-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_courselist_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='description',
            field=models.TextField(),
        ),
    ]
