# Generated by Django 4.1 on 2022-08-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_what_you_learn_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_you_learn',
            name='course',
        ),
        migrations.AddField(
            model_name='courselist',
            name='requirements_points',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='what_you_learn_points',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.DeleteModel(
            name='What_you_learn',
        ),
    ]
