# Generated by Django 4.1 on 2022-08-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_what_you_learn_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='requirements_points',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='what_you_learn_points',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
