# Generated by Django 4.1 on 2022-08-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_courselist_requirements_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='requirements_points',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='courselist',
            old_name='what_you_learn_points',
            new_name='what_you_learn',
        ),
    ]
