# Generated by Django 4.1 on 2022-08-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_requirements_points_courselist_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='courselist',
            name='what_you_learn',
        ),
    ]
