# Generated by Django 4.1 on 2022-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_courselist_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='requirements',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='what_you_learn',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
